// src/lib/components/layout/LayoutSharedHeader.svelte
<script lang="ts">
import AtomicBrandLogo from '$lib/components/atomic/AtomicBrandLogo.svelte';
import AtomicGradientBlur from '$lib/components/atomic/AtomicGradientBlur.svelte';
import { SITE } from '$lib/constants';
import type { ContentItem } from '$lib/content-types';

type Props = {
	type: 'index' | 'article';
	frontmatter?: ContentItem;
	title?: string;
};

let { type, frontmatter, title }: Props = $props();

const fallbackTitle = SITE.title;
const headingContent = $derived(type === 'article' ? (frontmatter?.title ?? title ?? fallbackTitle) : (title ?? fallbackTitle));
</script>

<div class="padding-standard grid h-60 grid-cols-10">
	<header class="col-span-base">
		<AtomicGradientBlur position="top" size="15rem" fixed={true} layers={5} className="z-0" />

		<div class="full-container relative z-10 uppercase">
			<div class="-translate-x-1/2 absolute bottom-0 left-1/2 w-full text-center">
				<div>{headingContent}</div>
			</div>
			<nav class="absolute bottom-0 left-0">
				<AtomicBrandLogo className="-translate-x-30 translate-y-6" />
			</nav>
		</div>
	</header>
</div>

// src/components/layout/layout-shared-header.tsx
/**
 * Layout Shared Header
 *
 * ## SUMMARY
 * Header with timeline-aware AnimatedReveal title and optional back button.
 *
 * ## RESPONSIBILITIES
 * - Render site or article header with animated title and navigation
 *
 * @module components/layout/layout-shared-header
 */

import { AnimatedStaggerBlur } from '@/components/animation/animated-stagger-blur';
import { AtomicBrandLogo } from '@/components/atomic/atomic-brand-logo';
import { AtomicGradientBlur } from '@/components/atomic/atomic-gradient-blur';
import { SITE } from '@/lib/constants';
import type { ContentItem } from '@/lib/mdx-types';

export interface LayoutSharedHeaderProps {
	type: 'index' | 'article';
	frontmatter?: ContentItem | undefined;
	title?: string | undefined;
}

export function LayoutSharedHeader({ type, frontmatter, title }: LayoutSharedHeaderProps) {
	const siteTitle = title ?? SITE.title;
	const headingContent = type === 'article' ? (frontmatter?.title ?? siteTitle) : siteTitle;
	const headingStageId = type === 'article' ? 'article-header' : 'index-header';
	const navStageId = type === 'article' ? 'article-header-nav' : 'index-header-nav';

	return (
		<div className="padding-standard grid h-60 grid-cols-10">
			<header className="col-span-base">
				<AtomicGradientBlur
					position="top"
					size="15rem"
					fixed={true}
					layers={5}
					className="z-0"
				/>

				<div className="full-container relative z-10 uppercase">
					<div className="-translate-x-1/2 absolute bottom-0 left-1/2 w-full text-center">
						<AnimatedStaggerBlur
							stageId={headingStageId}
							staggerDelay={50}
							blurStrength={5}
						>
							{headingContent}
						</AnimatedStaggerBlur>
					</div>
					<nav className="absolute bottom-0 left-0">
						<AnimatedStaggerBlur stageId={navStageId}>
							<AtomicBrandLogo
								className="-translate-x-30 translate-y-6"
								theme="light"
							/>
						</AnimatedStaggerBlur>
					</nav>
				</div>
			</header>
		</div>
	);
}
