// src/components/mdx/mdx-media_item.tsx
/**
 * MDX Media Item
 *
 * ## SUMMARY
 * Individual media item calculating aspect ratio and applying proportional flex-basis.
 *
 * ## RESPONSIBILITIES
 * - Load media dimensions, calculate aspect ratio, register with parent context
 *
 * ## KEY FLOWS
 * 1. Detect media type, load from BunnyCDN
 * 2. Extract dimensions on load event or cached media
 * 3. Calculate aspect ratio, register with parent
 * 4. Receive flex-basis from parent and apply to container
 *
 * @module components/mdx/mdx-media_item
 */

'use client';

import type { SyntheticEvent } from 'react';
import { useContext, useEffect, useId, useRef } from 'react';
import { MediaLayoutContext } from '@/components/mdx/mdx-media';
import { CDN } from '@/lib/constants';

export interface MdxMediaItemProps {
	src: string;
	alt?: string;
}

const VIDEO_EXTENSIONS = ['.webm'];

function isVideo(filename: string): boolean {
	const lowercase = filename.toLowerCase();
	return VIDEO_EXTENSIONS.some((ext) => lowercase.includes(ext));
}

function getLoadedAspectRatio(
	element: HTMLImageElement | HTMLVideoElement,
	isVideoFile: boolean,
): number {
	if (isVideoFile) {
		const video = element as HTMLVideoElement;
		if (video.readyState >= 1 && video.videoWidth > 0) {
			return video.videoWidth / video.videoHeight;
		}
	} else {
		const img = element as HTMLImageElement;
		if (img.complete && img.naturalWidth > 0) {
			return img.naturalWidth / img.naturalHeight;
		}
	}
	return 0;
}

export function MdxMediaItem({ src, alt }: MdxMediaItemProps) {
	const id = useId();
	const context = useContext(MediaLayoutContext);
	const mediaRef = useRef<HTMLImageElement | HTMLVideoElement>(null);
	const fullUrl = `${CDN.mediaUrl}${src}`;
	const isVideoFile = isVideo(src);

	const handleImageLoad = (event: SyntheticEvent<HTMLImageElement>) => {
		const img = event.currentTarget;
		const aspectRatio = img.naturalWidth / img.naturalHeight;

		if (context && Number.isFinite(aspectRatio) && aspectRatio > 0) {
			context.registerItem(id, aspectRatio);
		}
	};

	const handleVideoMetadata = (event: SyntheticEvent<HTMLVideoElement>) => {
		const video = event.currentTarget;
		const aspectRatio = video.videoWidth / video.videoHeight;

		if (context && Number.isFinite(aspectRatio) && aspectRatio > 0) {
			context.registerItem(id, aspectRatio);
		}
	};

	// biome-ignore lint/correctness/useExhaustiveDependencies: context omitted to prevent infinite loops
	useEffect(() => {
		const element = mediaRef.current;
		if (!element || !context) return;

		const aspectRatio = getLoadedAspectRatio(element, isVideoFile);

		if (Number.isFinite(aspectRatio) && aspectRatio > 0) {
			context.registerItem(id, aspectRatio);
		}
	}, [id, isVideoFile]);

	const flexBasis = context?.getFlexBasis(id) ?? '1';

	return (
		<div style={{ flexBasis, flexShrink: 0 }} className="h-full">
			{isVideoFile ? (
				<video
					ref={mediaRef as React.RefObject<HTMLVideoElement>}
					src={fullUrl}
					muted
					loop
					playsInline
					autoPlay
					onLoadedMetadata={handleVideoMetadata}
					className="media-fill"
				/>
			) : (
				// biome-ignore lint/performance/noImgElement: MDX content requires direct HTML img control
				<img
					ref={mediaRef as React.RefObject<HTMLImageElement>}
					src={fullUrl}
					alt={alt || ''}
					loading="lazy"
					onLoad={handleImageLoad}
					className="media-fill"
				/>
			)}
		</div>
	);
}

// src/lib/components/mdx/MdxMediaItem.svelte
<script lang="ts">
import { getContext, onMount } from 'svelte';
import { MEDIA_LAYOUT_CONTEXT, type MediaLayoutContextValue } from '$lib/components/mdx/mdx-context';
import { CDN } from '$lib/constants';

type Props = {
	src: string;
	alt?: string;
};

let { src, alt = '' }: Props = $props();

const context = getContext<MediaLayoutContextValue>(MEDIA_LAYOUT_CONTEXT);
const id = Math.random().toString(36).slice(2);
const fullUrl = $derived(`${CDN.mediaUrl}${src}`);
const isVideo = $derived(src.toLowerCase().includes('.webm') || src.toLowerCase().includes('.mp4'));

let imageRef = $state<HTMLImageElement | null>(null);
let videoRef = $state<HTMLVideoElement | null>(null);

const register = (aspectRatio: number) => {
	if (context && Number.isFinite(aspectRatio) && aspectRatio > 0) {
		context.registerItem(id, aspectRatio);
	}
};

const handleImageLoad = () => {
	if (!imageRef) return;
	const aspectRatio = imageRef.naturalWidth / imageRef.naturalHeight;
	register(aspectRatio);
};

const handleVideoMetadata = () => {
	if (!videoRef) return;
	const aspectRatio = videoRef.videoWidth / videoRef.videoHeight;
	register(aspectRatio);
};

onMount(() => {
	const element = isVideo ? videoRef : imageRef;
	if (!element) return;

	if (isVideo) {
		const video = element as HTMLVideoElement;
		if (video.readyState >= 1 && video.videoWidth > 0) {
			register(video.videoWidth / video.videoHeight);
		}
		return;
	}

	const img = element as HTMLImageElement;
	if (img.complete && img.naturalWidth > 0) {
		register(img.naturalWidth / img.naturalHeight);
	}
});

const flexBasis = $derived(context ? context.getFlexBasis(id) : '1');
</script>

<div class="h-full" style={`flex-basis: ${flexBasis}; flex-shrink: 0;`}>
	{#if isVideo}
		<video
			bind:this={videoRef}
			class="media-fill"
			src={fullUrl}
			autoplay
			muted
			loop
			playsinline
			preload="metadata"
			crossorigin="anonymous"
			referrerpolicy="origin"
			onloadedmetadata={handleVideoMetadata}
		></video>
	{:else}
		<img
			bind:this={imageRef}
			class="media-fill"
			src={fullUrl}
			alt={alt}
			loading="lazy"
			decoding="async"
			crossorigin="anonymous"
			referrerpolicy="origin"
			onload={handleImageLoad}
		/>
	{/if}
</div>
