// src/components/mdx/mdx-media.tsx
'use client';

/**
 * MDX Media
 *
 * ## SUMMARY
 * Aspect ratio-based media layout calculating optimal height and proportional flex-basis.
 *
 * ## RESPONSIBILITIES
 * - Measure container, collect child aspect ratios, calculate proportional flex-basis
 *
 * ## KEY FLOWS
 * 1. Measure container width, track resize events
 * 2. Children register aspect ratios after media load
 * 3. Calculate height: width ÷ sumOfAspectRatios
 * 4. Calculate flex-basis: (ratio ÷ sumOfRatios) × 100%
 *
 * @module components/mdx/mdx-media
 */

import { createContext, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { MdxMediaItem } from '@/components/mdx/mdx-media-item';
import { cn } from '@/lib/class';

export interface MdxMediaProps {
	src: string[];
	alt?: string;
}

export interface MediaLayoutContextValue {
	registerItem: (id: string, aspectRatio: number) => void;
	getFlexBasis: (id: string) => string;
}

export const MediaLayoutContext = createContext<MediaLayoutContextValue | null>(null);

export function MdxMedia({ src, alt }: MdxMediaProps) {
	const containerRef = useRef<HTMLDivElement>(null);
	const [containerWidth, setContainerWidth] = useState<number>(0);
	const [aspectRatios, setAspectRatios] = useState<Map<string, number>>(new Map());

	useEffect(() => {
		const container = containerRef.current;
		if (!container) return;

		let isMounted = true;

		setContainerWidth(container.offsetWidth);

		const resizeObserver = new ResizeObserver((entries) => {
			if (!isMounted) return;

			for (const entry of entries) {
				const width = entry.contentBoxSize?.[0]?.inlineSize ?? entry.contentRect.width;
				setContainerWidth(width);
			}
		});

		resizeObserver.observe(container);

		return () => {
			isMounted = false;
			resizeObserver.disconnect();
		};
	}, []);

	const registerItem = useCallback((id: string, aspectRatio: number) => {
		setAspectRatios((prev) => {
			const next = new Map(prev);
			next.set(id, aspectRatio);
			return next;
		});
	}, []);

	const getFlexBasis = useCallback(
		(id: string): string => {
			const ratio = aspectRatios.get(id);
			if (!ratio || aspectRatios.size === 0) {
				return '1';
			}

			const totalRatio = Array.from(aspectRatios.values()).reduce((sum, r) => sum + r, 0);
			const percentage = (ratio / totalRatio) * 100;
			return `${percentage}%`;
		},
		[aspectRatios],
	);

	const calculateHeight = (): number => {
		if (!containerWidth || aspectRatios.size === 0) {
			return 0;
		}

		const totalRatio = Array.from(aspectRatios.values()).reduce((sum, r) => sum + r, 0);

		return containerWidth / totalRatio;
	};

	const calculatedHeight = calculateHeight();
	const isLayoutReady = containerWidth > 0 && aspectRatios.size > 0 && calculatedHeight > 0;

	const contextValue = useMemo(
		(): MediaLayoutContextValue => ({
			registerItem,
			getFlexBasis,
		}),
		[registerItem, getFlexBasis],
	);

	return (
		<div className="grid grid-cols-10 padding-standard">
			<MediaLayoutContext.Provider value={contextValue}>
				<div
					ref={containerRef}
					className={cn(
						'flex col-start-1 col-span-full transition-opacity duration-300',
						isLayoutReady ? 'opacity-100' : 'opacity-0',
					)}
					style={calculatedHeight > 0 ? { height: `${calculatedHeight}px` } : {}}
				>
					{src.map((source) => (
						<MdxMediaItem key={source} src={source} alt={alt || ''} />
					))}
				</div>
			</MediaLayoutContext.Provider>
		</div>
	);
}

// src/lib/components/mdx/MdxMedia.svelte
<script lang="ts">
import { onMount, setContext } from 'svelte';
import MdxMediaItem from '$lib/components/mdx/MdxMediaItem.svelte';
import { MEDIA_LAYOUT_CONTEXT, type MediaLayoutContextValue } from '$lib/components/mdx/mdx-context';

type Props = {
	src: string[];
	alt?: string;
};

let { src, alt = '' }: Props = $props();

let container = $state<HTMLDivElement | null>(null);
let containerWidth = $state(0);
let aspectRatios = $state(new Map<string, number>());

const registerItem = (id: string, aspectRatio: number) => {
	aspectRatios = new Map(aspectRatios);
	aspectRatios.set(id, aspectRatio);
};

const getFlexBasis = (id: string): string => {
	const ratio = aspectRatios.get(id);
	if (!ratio || aspectRatios.size === 0) {
		return '1';
	}

	const totalRatio = Array.from(aspectRatios.values()).reduce((sum, value) => sum + value, 0);
	const percentage = (ratio / totalRatio) * 100;
	return `${percentage}%`;
};

setContext<MediaLayoutContextValue>(MEDIA_LAYOUT_CONTEXT, {
	registerItem,
	getFlexBasis,
});

const totalRatio = $derived(Array.from(aspectRatios.values()).reduce((sum, value) => sum + value, 0));
const calculatedHeight = $derived(containerWidth > 0 && totalRatio > 0 ? containerWidth / totalRatio : 0);
const isLayoutReady = $derived(containerWidth > 0 && totalRatio > 0 && calculatedHeight > 0);

onMount(() => {
	if (!container) return;

	const updateWidth = () => {
		containerWidth = container?.offsetWidth ?? 0;
	};

	updateWidth();

	const resizeObserver = new ResizeObserver((entries) => {
		for (const entry of entries) {
			const width = entry.contentBoxSize?.[0]?.inlineSize ?? entry.contentRect.width;
			containerWidth = width;
		}
	});

	resizeObserver.observe(container);

	return () => {
		resizeObserver.disconnect();
	};
});
</script>

<div class="padding-standard grid grid-cols-10">
	<div
		bind:this={container}
		class={`col-span-full col-start-1 flex transition-opacity duration-300 ${isLayoutReady ? "opacity-100" : "opacity-0"}`}
		style={calculatedHeight > 0 ? `height: ${calculatedHeight}px;` : ""}
	>
		{#each src as source (source)}
			<MdxMediaItem src={source} {alt} />
		{/each}
	</div>
</div>
