// src/components/layout/layout-shared-wrapper.tsx
/**
 * Layout Shared Wrapper
 *
 * ## SUMMARY
 * Main grid layout with header, footer, gradient blur, and content sections.
 *
 * ## RESPONSIBILITIES
 * - Provide consistent grid structure for index and article pages
 *
 * @module components/layout/layout-shared-wrapper
 */

import type { ReactNode } from 'react';
import { CoreScrollOverlay } from '@/components/core/core-scroll-overlay';
import { LayoutSharedFooter } from '@/components/layout/layout-shared-footer';
import { LayoutSharedHeader } from '@/components/layout/layout-shared-header';
import type { ContentItem } from '@/lib/mdx-types';

export interface LayoutSharedWrapperProps {
	type: 'index' | 'article';
	children: ReactNode;
	frontmatter?: ContentItem;
}

export function LayoutSharedWrapper({ type, children, frontmatter }: LayoutSharedWrapperProps) {
	return (
		<main className="full-container relative isolate min-h-screen overflow-x-hidden">
			<section data-section="header" className="relative z-10 w-full">
				<LayoutSharedHeader type={type} frontmatter={frontmatter} />
			</section>

			<section data-section="content" className="relative w-full">
				{children}
			</section>

			<section data-section="footer" className="relative z-40 w-full">
				<LayoutSharedFooter />
			</section>

			<CoreScrollOverlay pageType={type} />
		</main>
	);
}

// src/lib/components/layout/LayoutSharedWrapper.svelte
<script lang="ts">
import type { Snippet } from 'svelte';
import CoreScrollOverlay from '$lib/components/core/CoreScrollOverlay.svelte';
import LayoutSharedFooter from '$lib/components/layout/LayoutSharedFooter.svelte';
import LayoutSharedHeader from '$lib/components/layout/LayoutSharedHeader.svelte';
import type { ContentItem } from '$lib/content-types';

type Props = {
	type: 'index' | 'article';
	frontmatter?: ContentItem;
	children: Snippet;
};

let { type, frontmatter, children }: Props = $props();
</script>

<main class="full-container relative isolate min-h-screen overflow-x-hidden">
	<section data-section="header" class="relative z-10 w-full">
		<LayoutSharedHeader type={type} frontmatter={frontmatter} />
	</section>

	<section data-section="content" class="relative w-full">
		{@render children()}
	</section>

	<section data-section="footer" class="relative z-40 w-full">
		<LayoutSharedFooter />
	</section>

	<CoreScrollOverlay pageType={type} />
</main>
